### PR TITLE
Refactoring routes

### PR DESCRIPTION
**Pull request by ndevich**
- Removed ID queries 
- Template route now accepts an object rather than text
- PDFS are sorted now by general name then specific type
- Changed all lists in template to tables

---
This change is [Reviewable](https://reviewable.io/reviews/ndevich/pdf-generator-prototype/4)

### CODE REVIEW

**Comment by Boolos** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/PDFgenerator.ts, line 10 at r1](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KfMpmip2Muno96f7j_E:-KfMpmip2Muno96f7j_F:b-st2ty3) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/7ed9d4aa2b455c149dc30ae432eb887935788dbd/src/PDFgenerator.ts#L10)):*
> ```XML
> import db from './database/mongo';
> 
> const renderPDF = async (template_name: string, template_id: string, templateEntry: any, input: any): Promise<string> => { 
> ```

you might think about bundling the template related params into an object so you can do something like this: `const renderPDF = async (text: Template, input: any): Promise<string> => { .... }`.  That way, at the very least, you don't have to worry about the order of your parameters in your signature.

---

*[src/PDFgenerator.ts, line 18 at r1](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KfMr4OFc6pSV-SnkbGb:-KfMr4OFc6pSV-SnkbGc:b-r5ta1m) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/7ed9d4aa2b455c149dc30ae432eb887935788dbd/src/PDFgenerator.ts#L18)):*
> ```XML
> 
>     try {
>         mk(__dirname + "/pdfs/" + template_name  + "/" + template_id + "/");
> ```

consider using the js string interpolation syntax for all parametrized strings, i.e. ``mk(`${__dirname)/pdafs/${template_name}/${template_id}`)``

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-:-KfMshYr4_UrkyUoQURA:bnfp4nl)*

**Comment by ndevich** [comment]
*[src/PDFgenerator.ts, line 18 at r1](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KfMr4OFc6pSV-SnkbGb:-KgR0zcsYo0T-fn-cKck:b-896fix) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/7ed9d4aa2b455c149dc30ae432eb887935788dbd/src/PDFgenerator.ts#L18)):*
<details><summary><i>Previously, Boolos (Paul Martin) wrote…</i></summary><blockquote>

consider using the js string interpolation syntax for all parametrized strings, i.e. ``mk(`${__dirname)/pdafs/${template_name}/${template_id}`)``
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4)*

**Comment by ndevich** [comment]
*[src/PDFgenerator.ts, line 10 at r1](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KfMpmip2Muno96f7j_E:-KgR0yfNbNKrEJ1NfsCP:b-896fix) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/7ed9d4aa2b455c149dc30ae432eb887935788dbd/src/PDFgenerator.ts#L10)):*
<details><summary><i>Previously, Boolos (Paul Martin) wrote…</i></summary><blockquote>

you might think about bundling the template related params into an object so you can do something like this: `const renderPDF = async (text: Template, input: any): Promise<string> => { .... }`.  That way, at the very least, you don't have to worry about the order of your parameters in your signature.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4)*

**Comment by Boolos** [comment]
some good cleaning.  keep it up.

---

Reviewed 3 of 6 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/PDFgenerator.ts, line 10 at r4](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KgSXYqCNpTUKHip1T7s:-KgSXYqDGqaWgwks5SGy:b-9iwwbb) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/ba1d0a3f5669210daf0327e3644a8b7c0b8bd069/src/PDFgenerator.ts#L10)):*
> ```XML
>     id: string;
>     name: string;
>     template: string;
> ```

Think about renaming this property to something that is a bit more descriptive.  You've abstracted the concept of a "template", specifically an `ITemplate`, so each property of the template should describe some aspect of that template.  Maybe something as simple as `text`, then your code would read `template.text = '...'` instead of `template.template = '...'`

---

*[src/routes/PDF.ts, line 18 at r4](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KgSYtnoY4Ys5s9P513a:-KgSYtnoY4Ys5s9P513b:bm7l4eh) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/ba1d0a3f5669210daf0327e3644a8b7c0b8bd069/src/routes/PDF.ts#L18)):*
> ```XML
> }
> 
> interface Template {
> ```

Is this a duplicate type or truly different (from `ITemplate` that is)?

---

*[src/routes/PDF.ts, line 34 at r4](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KgSZQtoHpcTiA4wKzHi:-KgSZQtoHpcTiA4wKzHj:bmsaqyw) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/ba1d0a3f5669210daf0327e3644a8b7c0b8bd069/src/routes/PDF.ts#L34)):*
> ```XML
>          });
> 
>          router.get(this.prefix + '/:PDFname/:PDFid', jsonHelper({ pretty: true, param: 'pretty' }), async(ctx, next) => {
> ```

What's the reason for the double parametrized path: `/:PDFname/:PDFid`?  it seems like `/:PDFid` would be enough to uniquely identify a resource.

---

*[src/routes/PDF.ts, line 58 at r4](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KgS_Dripu4oHfhBazF4:-KgS_Dripu4oHfhBazF5:b5q14jh) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/ba1d0a3f5669210daf0327e3644a8b7c0b8bd069/src/routes/PDF.ts#L58)):*
> ```XML
> 
>             const date: Date = new Date();
>             const saveLocation: string = `${ctx.params.PDFname}_${ctx.params.PDFid}_${date.getUTCMonth()}_${date.getUTCDate()}_${date.getUTCFullYear()}_${date.getUTCMilliseconds()}.pdf`;
> ```

Might be a more succinct way to generate a unique file name, namely `PDFid`, unless `PDFid` is not guaranteed to be unique.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-:-KgS_c0T9Uhh3JovO6yI:b-ypna5c)*

**Comment by ndevich** [comment]
*[src/routes/PDF.ts, line 18 at r4](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KgSYtnoY4Ys5s9P513a:-KgUq1GGZyAwiobovrpW:bqmdddn) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/ba1d0a3f5669210daf0327e3644a8b7c0b8bd069/src/routes/PDF.ts#L18)):*
<details><summary><i>Previously, Boolos (Paul Martin) wrote…</i></summary><blockquote>

Is this a duplicate type or truly different (from `ITemplate` that is)?
</blockquote></details>

It's a duplicate. I think I'll make a separate module for the record and template interfaces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4)*

**Comment by ndevich** [comment]
*[src/routes/PDF.ts, line 34 at r4](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KgSZQtoHpcTiA4wKzHi:-KgUqWI3yoeqVzjIw4EA:b5r20d9) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/ba1d0a3f5669210daf0327e3644a8b7c0b8bd069/src/routes/PDF.ts#L34)):*
<details><summary><i>Previously, Boolos (Paul Martin) wrote…</i></summary><blockquote>

What's the reason for the double parametrized path: `/:PDFname/:PDFid`?  it seems like `/:PDFid` would be enough to uniquely identify a resource.
</blockquote></details>

I thought you had mentioned that there could be several versions of a certain type of pdf, so the PDFname would be for example BOL, and the PDFid would be BOLv1, BOLv2, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4)*

**Comment by ndevich** [comment]
*[src/routes/PDF.ts, line 58 at r4](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KgS_Dripu4oHfhBazF4:-KgUqrhoIBZST8go2g4c:bc4aq3y) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/ba1d0a3f5669210daf0327e3644a8b7c0b8bd069/src/routes/PDF.ts#L58)):*
<details><summary><i>Previously, Boolos (Paul Martin) wrote…</i></summary><blockquote>

Might be a more succinct way to generate a unique file name, namely `PDFid`, unless `PDFid` is not guaranteed to be unique.
</blockquote></details>

That goes along with what I mentioned about the double parameterized path, but if I was wrong about the version thing, then PDFid should be unique.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4)*

**Comment by ndevich** [comment]
*[src/PDFgenerator.ts, line 10 at r4](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KgSXYqCNpTUKHip1T7s:-KgUuETb4eKcYJGXIh7y:b-896fix) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/ba1d0a3f5669210daf0327e3644a8b7c0b8bd069/src/PDFgenerator.ts#L10)):*
<details><summary><i>Previously, Boolos (Paul Martin) wrote…</i></summary><blockquote>

Think about renaming this property to something that is a bit more descriptive.  You've abstracted the concept of a "template", specifically an `ITemplate`, so each property of the template should describe some aspect of that template.  Maybe something as simple as `text`, then your code would read `template.text = '...'` instead of `template.template = '...'`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4)*

**Comment by Boolos** [comment]
Reviewed 1 of 6 files at r5, 8 of 8 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/server.ts, line 14 at r6](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-Kga1gu1gaMVUFXaO-pc:-Kga1gu1gaMVUFXaO-pd:bl9gq90) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/c804d44f9e5a12834faecf454c678ea2c0697171/src/server.ts#L14)):*
> ```XML
>     private server: Koa;
> 
>     constructor() {
> ```

It's generally considered a good practice to only put initialization logic in your constructor (not things like establishing connections and async kind of behavior).  Ask me if you want details on why.  Consider implementing a `connect` method on the class so that you can separate object instantiation from starting up your server.

---

*[src/server.ts, line 26 at r6](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-Kga0fkS_I181IslBTot:-Kga0fkS_I181IslBTou:bw7equ1) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/c804d44f9e5a12834faecf454c678ea2c0697171/src/server.ts#L26)):*
> ```XML
> 
>         const connect = async (): Promise<any> => {
>             return await new Promise<any> ((res: any, rej: any) => {
> ```

I think if you `await` the promise it will "unbox" the value in the promise.  So in this case, the return type is `Promise<any>` but you're returning a value of type `any` (since you're awaiting the `new Promise<any>`.  If that makes sense.  Additionally, it looks like you're not returning anything, so returning type `void` may be more descriptive.

---

*[src/database/mongo.ts, line 12 at r6](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-Kga2Qlt8m1SigUxLGwh:-Kga2Qlt8m1SigUxLGwi:b9qgnhj) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/c804d44f9e5a12834faecf454c678ea2c0697171/src/database/mongo.ts#L12)):*
> ```XML
> 
> class DB {
>     public db: mongodb.Db;
> ```

This is just a class design thing, but you might not want to give public access to the underlying database.  the reason for creating a class to "wrap" the mongoDB is to be able to abstract away the db specific stuff, like with the methods you have for getting and updating (which is good).  If you want more details, holler at me.  

---

*[src/routes/PDF.ts, line 34 at r4](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KgSZQtoHpcTiA4wKzHi:-Kga48iO8aBwR6_1Huuz:b-dlcyng) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/ba1d0a3f5669210daf0327e3644a8b7c0b8bd069/src/routes/PDF.ts#L34)):*
<details><summary><i>Previously, ndevich (Nadine Devich) wrote…</i></summary><blockquote>

I thought you had mentioned that there could be several versions of a certain type of pdf, so the PDFname would be for example BOL, and the PDFid would be BOLv1, BOLv2, etc.
</blockquote></details>

Yeah there are a couple of different ways to model the concept of versioning.  Come talk to me for a discussion about that.  At a high level though, you basically have a collection of PDF entities.  there should be some way to uniquely identify them across the collection.  Doing some kind of composite key across `PDFname` and `PDFid` seems like unnecessary complexity.  A simple alternative might be something like:
```
Pdf {
  id: string
  name: string
  version: string
}
```
and now the path to find a given resource is something like `/pdfs/:id` or to find a particular named pdf `/pdfs?name='some_name'`
Holler at me if this doesn't make sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4)*

**Comment by ndevich** [comment]
*[src/database/mongo.ts, line 12 at r6](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-Kga2Qlt8m1SigUxLGwh:-KgaWs-cY4MT6y6ZKvq3:b-896fix) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/c804d44f9e5a12834faecf454c678ea2c0697171/src/database/mongo.ts#L12)):*
<details><summary><i>Previously, Boolos (Paul Martin) wrote…</i></summary><blockquote>

This is just a class design thing, but you might not want to give public access to the underlying database.  the reason for creating a class to "wrap" the mongoDB is to be able to abstract away the db specific stuff, like with the methods you have for getting and updating (which is good).  If you want more details, holler at me.  
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4)*

**Comment by ndevich** [comment]
*[src/server.ts, line 26 at r6](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-Kga0fkS_I181IslBTot:-KgaWuTZk053Kg7WpqaT:b-896fix) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/c804d44f9e5a12834faecf454c678ea2c0697171/src/server.ts#L26)):*
<details><summary><i>Previously, Boolos (Paul Martin) wrote…</i></summary><blockquote>

I think if you `await` the promise it will "unbox" the value in the promise.  So in this case, the return type is `Promise<any>` but you're returning a value of type `any` (since you're awaiting the `new Promise<any>`.  If that makes sense.  Additionally, it looks like you're not returning anything, so returning type `void` may be more descriptive.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4)*

**Comment by ndevich** [comment]
*[src/server.ts, line 14 at r6](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-Kga1gu1gaMVUFXaO-pc:-KgaWvaNJtdM8STvjfC2:b-896fix) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/c804d44f9e5a12834faecf454c678ea2c0697171/src/server.ts#L14)):*
<details><summary><i>Previously, Boolos (Paul Martin) wrote…</i></summary><blockquote>

It's generally considered a good practice to only put initialization logic in your constructor (not things like establishing connections and async kind of behavior).  Ask me if you want details on why.  Consider implementing a `connect` method on the class so that you can separate object instantiation from starting up your server.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4)*

**Comment by ndevich** [comment]
*[src/routes/PDF.ts, line 34 at r4](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4#-KgSZQtoHpcTiA4wKzHi:-KgpH4LQQ8z_cYQz5GYv:b3eupv1) ([raw file](https://github.com/ndevich/pdf-generator-prototype/blob/ba1d0a3f5669210daf0327e3644a8b7c0b8bd069/src/routes/PDF.ts#L34)):*
<details><summary><i>Previously, Boolos (Paul Martin) wrote…</i></summary><blockquote>

Yeah there are a couple of different ways to model the concept of versioning.  Come talk to me for a discussion about that.  At a high level though, you basically have a collection of PDF entities.  there should be some way to uniquely identify them across the collection.  Doing some kind of composite key across `PDFname` and `PDFid` seems like unnecessary complexity.  A simple alternative might be something like:
```
Pdf {
  id: string
  name: string
  version: string
}
```
and now the path to find a given resource is something like `/pdfs/:id` or to find a particular named pdf `/pdfs?name='some_name'`
Holler at me if this doesn't make sense.

</blockquote></details>

I'm not sure I understand, would the id in this case be BOLv1? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ndevich/pdf-generator-prototype/4)*

**Pull request merged**
